-- ═══════════════════════════════════════════════════════════════════════════
-- 04_insertion_periode_1.sql - Portrait de l'Âme (Périodes 1A et 1B)
-- Exécuter APRÈS 03_recreation_table_soul_periods.sql
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO cycle_vie_soul_periods (
    period_number, polarity, date_start, date_end, period_name, period_title,
    description_general, traits_positifs, traits_vigilance, professions_favorables,
    sante_vigilance, pays_affinites, conseils, message_cosmique, is_active
) VALUES 
-- PÉRIODE 1A
(1, 'A', '03-22', '04-19', 'Les Souverains', 'L''Âme Souveraine',
E'Vous portez en vous l''empreinte d''une âme qui a connu la grandeur. Dans les profondeurs de votre être réside le souvenir d''incarnations passées où vous avez occupé des positions d''honneur et de responsabilité. Vous avez goûté à la coupe pleine de la vie, entouré(e) de beauté et de luxe, et ces expériences ont sculpté votre essence actuelle.\n\nCe n''est pas un hasard si, depuis votre plus jeune âge, quelque chose en vous aspire naturellement vers les hauteurs. Une voix intérieure vous murmure que vous êtes destiné(e) à plus — non pas par orgueil, mais par reconnaissance instinctive de votre véritable nature.\n\nVous êtes animé(e) par un désir ardent et inextinguible d''atteindre une place élevée dans l''estime de ceux qui vous entourent — que ce soit dans le regard du public ou dans le cœur de vos proches. Ce n''est pas une simple ambition matérielle : c''est une soif de noblesse d''âme qui vous pousse constamment vers l''excellence.',
E'**L''Intégrité Innée**\nVous avez appris dans le passé que la tromperie, la fausseté et les pratiques contraires à l''éthique ne font que freiner votre progression. Pour cette raison, votre parole est généralement votre engagement. Quand vous donnez votre mot, il vaut de l''or.\n\n**Le Leadership Naturel**\nIl existe en vous une tendance naturelle à vouloir diriger et dominer. Vous excellez naturellement comme chef de file de tout plan, organisation ou groupe d''intérêts auxquels vous êtes associé(e).\n\n**L''Art de la Communication**\nVous choisissez généralement vos mots avec soin, tant à l''oral qu''à l''écrit. Votre personnalité possède un magnétisme naturel qui commande l''attention.\n\n**L''Aspiration Pragmatique**\nContrairement à beaucoup de rêveurs, vos ambitions ne sont pas brumeuses ou mystiques — elles sont pratiques et suivent une ligne de progression claire.',
E'**La Répugnance du Sordide**\nVous luttez naturellement contre tout ce qui est mesquin, bas ou offensant pour le bon goût. Cette sensibilité peut parfois vous rendre impatient(e) face à ceux qui ne partagent pas vos standards.\n\n**L''Impatience avec les \"Serviles\"**\nUne légère tendance peut émerger : une impatience subtile envers ceux qui n''aspirent pas à s''élever. Cultiver la patience et la compassion envers tous les chemins de vie est l''un de vos apprentissages.',
E'**Positions de Direction**\n• Directeur/Directrice d''organisations\n• Gestionnaire ou contrôleur de haut niveau\n• Maire, gouverneur ou tout poste officiel élevé\n• Positions judiciaires — magistrat, juge\n\n**Le Droit**\nVous possédez une excellente préparation et une faculté naturelle pour l''étude du droit.\n\n**Les Arts Créatifs**\nVous êtes attiré(e) par le travail des métaux comme concepteur et créateur de choses belles et magnifiques. Ou encore : designer de bâtiments, décorateur d''intérieurs, créateur de costumes élégants.',
E'• Affections du cœur — Prenez soin de votre système cardiovasculaire\n• Fatigue cérébrale — Possible surmenage mental\n• Sensibilité oculaire — Protégez vos yeux\n• Tendance aux états fébriles',
E'Certains lieux sur Terre résonnent particulièrement avec les vibrations de votre âme :\n• Chaldée et Phénicie (Moyen-Orient antique)\n• Italie, particulièrement les régions historiques\n• Sicile\n• Suisse\n• Écosse',
E'1. **Embrassez Votre Aspiration Naturelle** — Cette voix intérieure est votre guide cosmique.\n2. **Cultivez la Patience** — Étendez votre noblesse d''âme à TOUS.\n3. **Équilibrez le Pouvoir avec l''Humilité** — Les meilleurs leaders sont ceux qui servent.\n4. **Protégez Votre Cœur** — Apprenez l''art du repos et de la méditation.',
E'Vous êtes venu(e) dans cette vie avec une mission claire : incarner la noblesse d''esprit et inspirer les autres par votre exemple. Votre chemin n''est pas celui de la fortune pour la fortune, mais celui de la grandeur de caractère qui élève tous ceux qui croisent votre route.',
true),

-- PÉRIODE 1B
(1, 'B', '03-22', '04-19', 'Les Artistes Souverains', 'L''Âme Artiste Raffinée',
E'Comme vos semblables nés dans cette même fenêtre cosmique, vous portez en vous le souvenir d''une grandeur passée. Mais là où certains ont conquis par la force, vous avez conquis par la grâce. Vos incarnations antérieures vous ont enseigné que la véritable noblesse réside dans le raffinement de l''esprit et la délicatesse de l''expression.\n\nVous êtes venu(e) dans cette vie avec une mémoire subtile de cours royales où l''art, la musique et le théâtre étaient les langages du pouvoir. Cette empreinte cosmique vous pousse naturellement vers l''excellence esthétique plutôt que vers la conquête brutale.\n\nVous partagez avec vos proches cosmiques cette aspiration vers les hauteurs et la reconnaissance, mais votre chemin vers ces sommets est différent. Là où d''autres foncent avec l''énergie du guerrier, vous avancez avec la grâce du diplomate et la subtilité de l''artiste.',
E'**La Gentillesse Naturelle**\nVous êtes plus gentil(le) que ceux qui partagent votre groupe cosmique. Votre approche est douce, souriante et subtile.\n\n**La Détermination Silencieuse**\nSous votre extérieur doux se cache une détermination que certains pourraient qualifier d''obstination. Quand vous avez décidé quelque chose, vous y tenez avec une ténacité remarquable.\n\n**Le Sens Esthétique Inné**\nVous possédez un œil naturel pour ce qui est beau, harmonieux et bien proportionné.\n\n**La Diplomatie Naturelle**\nVous savez obtenir ce que vous voulez sans créer de conflit. Votre approche subtile désarme souvent ceux qui s''attendaient à une opposition frontale.',
E'**La Tentation du Retrait**\nVotre nature délicate peut parfois vous pousser à éviter les confrontations nécessaires. Apprenez à vous affirmer quand la situation l''exige.\n\n**L''Obstination Cachée**\nCette détermination silencieuse peut parfois se transformer en entêtement improductif. Sachez reconnaître quand il est temps de lâcher prise.',
E'**Les Arts et la Création**\n• Artiste peintre, sculpteur ou designer\n• Acteur/Actrice de théâtre ou de cinéma\n• Musicien(ne) ou compositeur\n• Créateur/Créatrice de mode\n\n**Les Métiers du Raffinement**\n• Décorateur/Décoratrice d''intérieur\n• Galeriste ou conservateur de musée\n• Critique d''art ou de spectacle\n• Directeur/Directrice artistique',
E'• Affections du cœur — Votre sensibilité peut affecter ce centre vital\n• Fatigue cérébrale — L''intensité créative peut épuiser\n• Sensibilité oculaire — Les artistes sollicitent beaucoup leurs yeux\n• Tendance aux états fébriles',
E'Les mêmes terres résonnent avec votre âme que pour vos proches cosmiques, avec une sensibilité particulière pour les centres artistiques :\n• L''Italie et ses trésors de la Renaissance\n• La Sicile et ses influences multiples\n• La Suisse et son raffinement\n• L''Écosse et ses paysages dramatiques\n• Les anciennes terres de Chaldée et Phénicie',
E'1. **Nourrissez Votre Créativité** — L''art est votre langage, ne le négligez jamais.\n2. **Affirmez-vous avec Grâce** — La douceur n''exclut pas la fermeté.\n3. **Choisissez Vos Batailles** — Toutes les confrontations ne méritent pas votre énergie.\n4. **Célébrez Votre Unicité** — Votre approche subtile est un don, pas une faiblesse.',
E'Vous êtes venu(e) dans cette vie pour prouver que la grâce et la détermination peuvent coexister. Votre mission est de montrer au monde qu''on peut atteindre les sommets par le raffinement de l''esprit plutôt que par la force brute. Laissez votre art parler pour vous.',
true);

SELECT '✅ PÉRIODE 1 (1A + 1B) INSÉRÉE' as status;
SELECT period_number, polarity, period_name, LENGTH(conseils) as conseils_len, LENGTH(message_cosmique) as msg_len
FROM cycle_vie_soul_periods WHERE period_number = 1;
