INSERT INTO life_phase_periods (phase_number, phase_name, age_start, age_end, theme, full_content, impacts, questions_reflection) VALUES
(1, 'L''Enfance', 0, 7, 'Formation de l''identité', '-- VOIR content/phase_01_enfance.md --', 
 ARRAY['Sécurité émotionnelle', 'Relation à l''autorité', 'Schémas d''attachement', 'Confiance en la vie'],
 ARRAY['Quels souvenirs marquants gardez-vous?', 'Comment ces expériences influencent-elles vos choix?']),
(2, 'La Croissance', 7, 14, 'Socialisation et apprentissage', '-- VOIR content --',
 ARRAY['Rapport à l''apprentissage', 'Place dans les groupes', 'Amitiés', 'Estime de soi'],
 ARRAY['Étiez-vous populaire ou isolé?', 'Comment viviez-vous l''apprentissage?']),
(3, 'L''Adolescence', 14, 21, 'Quête d''indépendance', '-- VOIR content --',
 ARRAY['Relation à l''autorité', 'Premières amours', 'Orientation professionnelle', 'Rapport à la liberté'],
 ARRAY['Comment s''est passée votre rébellion?', 'Quelles passions avez-vous découvertes?']),
(4, 'Le Jeune Adulte', 21, 28, 'Construction de vie', '-- VOIR content --',
 ARRAY['Trajectoire professionnelle', 'Choix relationnels', 'Indépendance financière', 'Vision de réussite'],
 ARRAY['Les choix de carrière vous satisfont-ils?', 'Les engagements étaient-ils réfléchis?']),
(5, 'La Première Maturité', 28, 35, 'Stabilisation', '-- VOIR content --',
 ARRAY['Sentiment de sécurité', 'Équilibre travail-vie', 'Responsabilités familiales', 'Statut social'],
 ARRAY['Avez-vous atteint la stabilité recherchée?', 'Cette stabilité vous satisfait-elle?']),
(6, 'La Crise du Milieu', 35, 42, 'Réévaluation', '-- VOIR content --',
 ARRAY['Sens de la vie', 'Remises en question', 'Aspirations profondes', 'Authenticité'],
 ARRAY['Vivez-vous la vie que vous vouliez?', 'Quels rêves reprendre?']),
(7, 'La Sagesse Émergente', 42, 49, 'Transmission', '-- VOIR content --',
 ARRAY['Rôle de mentor', 'Contribution sociale', 'Héritage', 'Sagesse acquise'],
 ARRAY['Que transmettez-vous?', 'Quel héritage souhaitez-vous laisser?']),
(8, 'L''Accomplissement', 49, 56, 'Récolte des fruits', '-- VOIR content --',
 ARRAY['Position d''influence', 'Reconnaissance sociale', 'Liberté financière', 'Légitimité'],
 ARRAY['Récoltez-vous ce que vous avez semé?', 'Comment utilisez-vous votre influence?']),
(9, 'La Sagesse Profonde', 56, 63, 'Héritage spirituel', '-- VOIR content --',
 ARRAY['Transmission spirituelle', 'Réconciliation', 'Paix intérieure', 'Legs'],
 ARRAY['Quel héritage spirituel transmettez-vous?', 'Êtes-vous en paix avec votre parcours?']),
(10, 'La Transcendance', 63, 100, 'Paix intérieure', '-- VOIR content --',
 ARRAY['Acceptation', 'Sérénité', 'Sagesse accomplie', 'Préparation à la transition'],
 ARRAY['Êtes-vous réconcilié avec la vie?', 'Quels conseils donneriez-vous aux jeunes?']);
